theme: jekyll-theme-minimal
title: Mayowa-Oluwanimotele
description: A Front-end Web Developer mainly focuses on creating the user interface for websites and Web Applications that contribute to the success of the final result, products.
